Use SecKeychainCopyDomainSearchList to find system keychain
jamf/Haversack pull request #3
Opened 2024-01-04 22:28 UTC by mlink

It's been mentioned [on the forums](https://developer.apple.com/forums/thread/704034) that hardcoding a path to the system keychain may not be ideal. This PR addresses that by using the Security frameworks methods to locate the system keychain. To retain compatibility any errors from attempting to locate the system keychain will default to previous behavior and return a reference to `KeychainFile` that will attempt to find the system keychain at `/Library/Keychains/System.keychain`.

2024-01-05 09:05 UTC, taher-mosbah approved these changes

2024-01-05 14:06 UTC, JacobHearst requested changes
LGTM, just some linting errors to clean up

2024-01-05 15:41 UTC, mlink commented
> LGTM, just some linting errors to clean up

If I could push…
```
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/ml_use_keychain_search_list_to_find_system_keychain.
remote: error: Cannot change this locked branch
```

Do I need to submit another PR to merge into this one?

2024-01-05 16:11 UTC, JacobHearst commented
> > LGTM, just some linting errors to clean up
> 
> If I could push…
> 
> ```
> remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
> remote: error: GH006: Protected branch update failed for refs/heads/ml_use_keychain_search_list_to_find_system_keychain.
> remote: error: Cannot change this locked branch
> ```
> 
> Do I need to submit another PR to merge into this one?

Uhhhh not sure why this branch is locked... let me take a look through the repo settings

2024-01-05 17:52 UTC, JacobHearst commented
@mlink The reason branches are locked is that the preferred workflow for internal _and_ external contributors is to fork this repo and make a PR that way. Please close this PR, fork Haversack, and make your changes that way.

2024-01-05 19:22 UTC, closed without merging

2024-01-09 07:55 UTC, macblazer commented
The [Contributing](https://github.com/jamf/Haversack#contributing) section of the README does say to fork this repo and make your changes in the fork.